import UIProvider from '@/providers/UIProvider'
import './globals.css'
import { Figtree } from 'next/font/google'
import ModelProvider from '@/providers/ModelProvider'

const figtree = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <ModelProvider />
        <UIProvider>
          {/* <main className='dark text-foreground'> */}

          {children}
          {/* </main> */}
        </UIProvider>
      </body>
    </html>
  )
}
